flowchart TB
    subgraph " "
    v0["Channel.fromPath"]
    v1["Channel.fromPath"]
    v2["Channel.fromPath"]
    v3["Channel.fromPath"]
    v4["Channel.fromPath"]
    v5["Channel.fromPath"]
    v6["Channel.fromPath"]
    v7["Channel.fromPath"]
    v8["strict"]
    v16["strict"]
    v24["strict"]
    v32["strict"]
    v40["strict"]
    v48["strict"]
    v56["strict"]
    v64["strict"]
    v72["strict"]
    v80["strict"]
    v88["strict"]
    v96["strict"]
    v104["strict"]
    v112["strict"]
    v157["predictorName"]
    v160["predictorName"]
    v163["predictorName"]
    v166["predictorName"]
    v169["predictorName"]
    v172["predictorName"]
    v175["predictorName"]
    v178["predictorName"]
    v181["predictorName"]
    v184["predictorName"]
    v187["predictorName"]
    v190["predictorName"]
    v193["predictorName"]
    v196["predictorName"]
    end
    subgraph predict
    v9([alignIdentityFree])
    v17([alignIdentityStrict])
    v25([alignCoincidencesFree])
    v33([alignCoincidencesStrict])
    v41([alignSimilarityBlosum62Free])
    v49([alignSimilarityBlosum62Strict])
    v57([alignSimilarityPam250Free])
    v65([alignSimilarityPam250Strict])
    v73([alignGonnet92Free])
    v81([alignGonnet92Strict])
    v89([alignGlobalFree])
    v97([alignGlobalStrict])
    v105([alignLocalFree])
    v113([alignLocalStrict])
    v120(( ))
    v122(( ))
    v124(( ))
    v126(( ))
    v128(( ))
    v130(( ))
    v132(( ))
    v134(( ))
    v136(( ))
    v138(( ))
    v140(( ))
    v142(( ))
    v144(( ))
    v146(( ))
    end
    subgraph " "
    v10[" "]
    v11[" "]
    v12[" "]
    v13[" "]
    v14[" "]
    v15[" "]
    v18[" "]
    v19[" "]
    v20[" "]
    v21[" "]
    v22[" "]
    v23[" "]
    v26[" "]
    v27[" "]
    v28[" "]
    v29[" "]
    v30[" "]
    v31[" "]
    v34[" "]
    v35[" "]
    v36[" "]
    v37[" "]
    v38[" "]
    v39[" "]
    v42[" "]
    v43[" "]
    v44[" "]
    v45[" "]
    v46[" "]
    v47[" "]
    v50[" "]
    v51[" "]
    v52[" "]
    v53[" "]
    v54[" "]
    v55[" "]
    v58[" "]
    v59[" "]
    v60[" "]
    v61[" "]
    v62[" "]
    v63[" "]
    v66[" "]
    v67[" "]
    v68[" "]
    v69[" "]
    v70[" "]
    v71[" "]
    v74[" "]
    v75[" "]
    v76[" "]
    v77[" "]
    v78[" "]
    v79[" "]
    v82[" "]
    v83[" "]
    v84[" "]
    v85[" "]
    v86[" "]
    v87[" "]
    v90[" "]
    v91[" "]
    v92[" "]
    v93[" "]
    v94[" "]
    v95[" "]
    v98[" "]
    v99[" "]
    v100[" "]
    v101[" "]
    v102[" "]
    v103[" "]
    v106[" "]
    v107[" "]
    v108[" "]
    v109[" "]
    v110[" "]
    v111[" "]
    v114[" "]
    v115[" "]
    v116[" "]
    v117[" "]
    v118[" "]
    v119[" "]
    v150[" "]
    v152[" "]
    v154[" "]
    v156[" "]
    v159[" "]
    v162[" "]
    v165[" "]
    v168[" "]
    v171[" "]
    v174[" "]
    v177[" "]
    v180[" "]
    v183[" "]
    v186[" "]
    v189[" "]
    v192[" "]
    v195[" "]
    v198[" "]
    v201[" "]
    end
    subgraph evaluateAlignments
    v148([sortMuscleFasta])
    v149([sortClustalFasta])
    v151([sortMAFFTFasta])
    v153([sortTCoffeeFasta])
    v155([sortKAlignFasta])
    v158([computeCoincidencesBaliScoreFree])
    v161([computeIdentityBaliScoreFree])
    v164([computeSimilarityBlosum62BaliScoreFree])
    v167([computeSimilarityPam250BaliScoreFree])
    v170([computeSimilarityGonnet92BaliScoreFree])
    v173([computeGlobalBaliScoreFree])
    v176([computeLocalBaliScoreFree])
    v179([computeCoincidencesBaliScoreStrict])
    v182([computeIdentityBaliScoreStrict])
    v185([computeSimilarityBlosum62BaliScoreStrict])
    v188([computeSimilarityPam250BaliScoreStrict])
    v191([computeSimilarityGonnet92BaliScoreStrict])
    v194([computeGlobalBaliScoreStrict])
    v197([computeLocalBaliScoreStrict])
    v199([computeMumsaOverlapScore])
    v200([plotMumsaOverlap])
    end
    v0 --> v9
    v0 --> v17
    v0 --> v25
    v0 --> v33
    v0 --> v41
    v0 --> v49
    v0 --> v57
    v0 --> v65
    v0 --> v73
    v0 --> v81
    v0 --> v89
    v0 --> v97
    v0 --> v105
    v0 --> v113
    v1 --> v148
    v1 --> v149
    v1 --> v151
    v1 --> v153
    v1 --> v155
    v1 --> v199
    v2 --> v158
    v2 --> v161
    v2 --> v164
    v2 --> v167
    v2 --> v170
    v2 --> v173
    v2 --> v176
    v2 --> v179
    v2 --> v182
    v2 --> v185
    v2 --> v188
    v2 --> v191
    v2 --> v194
    v2 --> v197
    v3 --> v149
    v3 --> v199
    v4 --> v155
    v4 --> v199
    v5 --> v151
    v5 --> v199
    v6 --> v148
    v7 --> v153
    v7 --> v199
    v8 --> v9
    v9 --> v15
    v9 --> v14
    v9 --> v13
    v9 --> v12
    v9 --> v11
    v9 --> v10
    v9 --> v124
    v16 --> v17
    v17 --> v23
    v17 --> v22
    v17 --> v21
    v17 --> v20
    v17 --> v19
    v17 --> v18
    v17 --> v126
    v24 --> v25
    v25 --> v31
    v25 --> v30
    v25 --> v29
    v25 --> v28
    v25 --> v27
    v25 --> v26
    v25 --> v120
    v32 --> v33
    v33 --> v39
    v33 --> v38
    v33 --> v37
    v33 --> v36
    v33 --> v35
    v33 --> v34
    v33 --> v122
    v40 --> v41
    v41 --> v47
    v41 --> v46
    v41 --> v45
    v41 --> v44
    v41 --> v43
    v41 --> v42
    v41 --> v128
    v48 --> v49
    v49 --> v55
    v49 --> v54
    v49 --> v53
    v49 --> v52
    v49 --> v51
    v49 --> v50
    v49 --> v130
    v56 --> v57
    v57 --> v63
    v57 --> v62
    v57 --> v61
    v57 --> v60
    v57 --> v59
    v57 --> v58
    v57 --> v132
    v64 --> v65
    v65 --> v71
    v65 --> v70
    v65 --> v69
    v65 --> v68
    v65 --> v67
    v65 --> v66
    v65 --> v134
    v72 --> v73
    v73 --> v79
    v73 --> v78
    v73 --> v77
    v73 --> v76
    v73 --> v75
    v73 --> v74
    v73 --> v136
    v80 --> v81
    v81 --> v87
    v81 --> v86
    v81 --> v85
    v81 --> v84
    v81 --> v83
    v81 --> v82
    v81 --> v138
    v88 --> v89
    v89 --> v95
    v89 --> v94
    v89 --> v93
    v89 --> v92
    v89 --> v91
    v89 --> v90
    v89 --> v140
    v96 --> v97
    v97 --> v103
    v97 --> v102
    v97 --> v101
    v97 --> v100
    v97 --> v99
    v97 --> v98
    v97 --> v142
    v104 --> v105
    v105 --> v111
    v105 --> v110
    v105 --> v109
    v105 --> v108
    v105 --> v107
    v105 --> v106
    v105 --> v144
    v112 --> v113
    v113 --> v119
    v113 --> v118
    v113 --> v117
    v113 --> v116
    v113 --> v115
    v113 --> v114
    v113 --> v146
    v148 --> v199
    v149 --> v150
    v151 --> v152
    v153 --> v154
    v155 --> v156
    v157 --> v158
    v120 --> v158
    v158 --> v159
    v160 --> v161
    v124 --> v161
    v161 --> v162
    v163 --> v164
    v128 --> v164
    v164 --> v165
    v166 --> v167
    v132 --> v167
    v167 --> v168
    v169 --> v170
    v136 --> v170
    v170 --> v171
    v172 --> v173
    v140 --> v173
    v173 --> v174
    v175 --> v176
    v144 --> v176
    v176 --> v177
    v178 --> v179
    v122 --> v179
    v179 --> v180
    v181 --> v182
    v126 --> v182
    v182 --> v183
    v184 --> v185
    v130 --> v185
    v185 --> v186
    v187 --> v188
    v134 --> v188
    v188 --> v189
    v190 --> v191
    v138 --> v191
    v191 --> v192
    v193 --> v194
    v142 --> v194
    v194 --> v195
    v196 --> v197
    v146 --> v197
    v197 --> v198
    v120 --> v199
    v122 --> v199
    v124 --> v199
    v126 --> v199
    v128 --> v199
    v130 --> v199
    v132 --> v199
    v134 --> v199
    v136 --> v199
    v138 --> v199
    v140 --> v199
    v142 --> v199
    v144 --> v199
    v146 --> v199
    v199 --> v200
    v200 --> v201
